# File: code/pipelines/create-subcr.yml
trigger: none
pr: none

parameters:
  - name: subscriptionDisplayName
    type: string
    default: "spn-sub-001"

  - name: aliasName
    type: string
    default: "spn-sub-001"

  - name: billingScope
    type: string
    default: "/providers/Microsoft.Billing/billingAccounts/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY/billingProfiles/ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ/invoiceSections/WWWWWWWW-WWWW-WWWW-WWWW-WWWWWWWWWWWW"

  - name: managementGroupId
    type: string
    default: "contoso-platform"

  - name: workload
    type: string
    default: "Production"

  - name: tags
    type: string
    default: "env=platform owner=azure-team"

variables:
  azureServiceConnection: "azure-spn-sc"

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: Create_Subscription
  displayName: "Create & Assign Subscription"
  jobs:
  - job: create
    displayName: "Provision Subscription, Move to MG, Tag"
    steps:

    - task: Bash@3
      displayName: "Update Azure CLI on agent"
      inputs:
        targetType: "inline"
        script: |
          set -e
          echo "Updating Azure CLI on hosted agent..."
          sudo apt-get update -y
          sudo apt-get install -y azure-cli
          az version

    - task: AzureCLI@2
      displayName: "Create subcr (alias + wait)"
      inputs:
        azureSubscription: "$(azureServiceConnection)"
        scriptType: "bash"
        scriptLocation: "scriptPath"
        scriptPath: "code/scripts/create-subcr/create_subcr.sh"
        arguments: >
          ${{ parameters.subscriptionDisplayName }}
          ${{ parameters.aliasName }}
          ${{ parameters.billingScope }}
          ${{ parameters.workload }}
      name: CreateStep

    - task: AzureCLI@2
      displayName: "Finalize subcr (MG + tags + summary)"
      inputs:
        azureSubscription: "$(azureServiceConnection)"
        scriptType: "bash"
        scriptLocation: "scriptPath"
        scriptPath: "code/scripts/create-subcr/finalize_subcr.sh"
        arguments: >
          $(CreateStep.newSubscriptionId)
          ${{ parameters.managementGroupId }}
          "${{ parameters.tags }}"
